### ISSUE TITLE
Component: Document

### ISSUE THREAD

**Issue by kyhryt** [USAJOBS/design-system#19]
Hey Matt, 

Here are the Thumbnails and Alerts in PNG format. You can take a look at the PSD's here:

smb://wdcvfxsvs01/USAJOBS-GOVT/Program Management/Outreach, Communications and Usability/Outreach, Communications & Usability/Usability/Design/Application Guide/Style Guide

Let me know if you need anything else, 
Kyhry. 

![alerts-04](https://cloud.githubusercontent.com/assets/15234468/10826577/bcded78c-7e40-11e5-85d6-1f43975e00e4.png)
![thumbnails-04](https://cloud.githubusercontent.com/assets/15234468/10826578/bce279aa-7e40-11e5-9670-baa8b616c58f.png)

* [x] Default
* [x] Hover
* [x] Selected
* [ ] Focus
* [x] Add
* [ ] Disabled
* [ ] Corrupt
* [ ] Incomplete
* [x] Loading
* [x] Placeholder

**Comment by humancompanion** [comment]
I've already taken care of the alerts in issue #5. So this issue will be for the Thumbnails.

**Comment by humancompanion** [comment]
We've renamed the Thumbnails component to "Document" since it represents a document. I just made some changes to this component that allow for single-select (radio input) or multi-select (checkbox input). We wanted to differentiate both functionally and visually when only one, or more than one, document can be selected.
